const MediaHouse = [
  {
    id : 1,
    name: "Berita Harian",
    img: "https://www.bharian.com.my/assets/logo.png?id=77d98e31e7c7feb58fa2",
    width: "70px",
    padding: "0",
    background: "none",
  },

  {
    id : 2,
    name: "Utusan Malaysia",
    img: "https://upload.wikimedia.org/wikipedia/commons/3/32/Logo_Utusan_Malaysia_2020.png",
    width: "100px",
    padding: "0",
    background: "none",
  },

  {
    id : 3,
    name: "Sinar Harian",
    img: "https://www.sinarharian.com.my/themes/sinarharian/images/LOGO-SINAR-HARIAN.svg",
    width: "90px",
    padding: "5px",
    background: "#E3130E",
  },
  {
    id : 4,
    name: "Bernama",
    img: "https://bernama.com/bm/img/logobernama_00.png",
    width: "130px",
    padding: "5px",
    background: "#fff",
  },
  {
    id : 5,
    name: "The Star",
    img: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Star-masthead-logo.png",
    width: "70px",
    padding: "5px 10px",
    background: "#DA2128",
  },
  {
    id : 6,
    name: "The Edge Markets",
    img: "https://assets.theedgemarkets.com/logo_0_0.png",
    width: "80px",
    padding: "5px",
    background: "#fff",
  },
  {
    id : 7,
    name: "Free Malaysia Today",
    img: "https://s3media.freemalaysiatoday.com/wp-content/uploads/2021/02/desktop_272x90-new-logo-2021-1.png",
    width: "120px",
    padding: "5px",
    background: "none",
  },
  {
    id : 8,
    name: "Malay Mail",
    img: "https://www.pngitem.com/pimgs/m/90-908685_malay-mail-hd-png-download.png",
    width: "150px",
    padding: "0",
    background: "none",
  },
  {
    id : 9,
    name: "Malaysia Kini",
    img: "https://static01.malaysiakini.com/img/mk-logo/mk-logo-en.svg",
    width: "120px",
    padding: "5px",
    background: "#fff",
  },
  {
    id : 10,
    name: "Harian Metro",
    img: "https://assets.hmetro.com.my/assets/logo1@2x.png?id=78560759146a70b6eba4",
    width: "120px",
    padding: "5px",
    background: "#013365",
  },
  {
    id: 11,
    name: "Astro Awani",
    img: "https://de-digital-fortress-stg-assets.eco.astro.com.my/staging/2a4ea8d2d2e75e576b4a7de761113bc3.png",
    width: "90px",
    padding: "0",
    background: "#none",
  },
];

export default MediaHouse;
